title: Rodrigo Barros Portfolio
#logo: /assets/img/headshot_small.jpeg
description: Clubs Coordinator @ SSF | Computer Programming Student at Seneca Polytechnic 
show_downloads: true
theme: jekyll-theme-minimal
